#' rebuild a package
#'
#' @param sentences the sentences
#'
#'
#' @export
stripPlurals <- function(sentences){
  words <- gsub("-"," ",sentences)
  words <- gsub("[^A-Za-z0-9_]"," ",words)
  words <- gsub("(bs |bs$)","b ",words)
  words <- gsub("(cs |cs$)","c ",words)
  words <- gsub("(ds |ds$)","d ",words)
  words <- gsub("(fs |fs$)","f ",words)
  words <- gsub("(gs |gs$)","g ",words)
  words <- gsub("(js |js$)","j ",words)
  words <- gsub("(ks |ks$)","k ",words)
  words <- gsub("(ls |ls$)","l ",words)
  words <- gsub("(ms |ms$)","m ",words)
  words <- gsub("(ns |ns$)","n ",words)
  words <- gsub("(os |os$)","o ",words)
  words <- gsub("(ps |ps$)","p ",words)
  words <- gsub("(qs |qs$)","q ",words)
  words <- gsub("(rs |rs$)","r ",words)
  words <- gsub("(ts |ts$)","t ",words)
  words <- gsub("(vs |vs$)","v ",words)
  words <- gsub("(ws |ws$)","w ",words)
  words <- gsub("(xs |xs$)","x ",words)
  words <- gsub("(ys |ys$)","y ",words)
  words <- gsub("(zs |zs$)","z ",words)
  words <- gsub("(aes |aes$)","ae ",words)
  words <- gsub("(bes |bes$)","be ",words)
  words <- gsub("(ces |ces$)","ce ",words)
  words <- gsub("(des |des$)","de ",words)
  words <- gsub("(eas |eas$)","ea ",words)
  words <- gsub("(ees |ees$)","ee ",words)
  words <- gsub("(fes |fes$)","fe ",words)
  words <- gsub("(ges |ges$)","ge ",words)
  words <- gsub("(hes |hes$)","ge ",words)
  words <- gsub("(kes |kes$)","ke ",words)
  words <- gsub("(les |les$)","le ",words)
  words <- gsub("(mes |mes$)","me ",words)
  words <- gsub("(nes |nes$)","ne ",words)
  words <- gsub("(oes |oes$)","oe ",words)
  words <- gsub("(pes |pes$)","pe ",words)
  words <- gsub("(res |res$)","re ",words)
  words <- gsub("(ses |ses$)","se ",words)
  words <- gsub("(tes |tes$)","te ",words)
  words <- gsub("(ues |ues$)","ue ",words)
  words <- gsub("(ves |ves$)","ve ",words)
  words <- gsub("(xes |xes$)","x ",words)
  words <- gsub("(ies |ies$)","y ",words)
  words <- gsub("(yes |yes$)","ye ",words)
  words <- gsub("(zes |zes$)","ze ",words)
  words <- gsub("[ ]+"," ",words)
}
